### ISSUE TITLE
The extra_env_vars appears broken for cori.yaml

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-scripts#78]
There seems to be an issue with the `extra_env_vars` feature. The feature is used under ./config/cori.yaml:
```
  intel:
     test_time: "3:00:00"
     versions: 
       19.1.2: 
         compiler: intel/19.1.2.254          
         netcdf: cray-netcdf/4.6.3.2
         mpi:
           mpiuni: 
             module: None
           mpi: 
             module: cray-mpich/7.7.19
         extra_env_vars:
             var1: ESMF_NETCDF_LIBS="-lnetcdf"
             var2: ESMF_NETCDFF_LIBS="-lnetcdff"
             var3: PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/cray/pe/hdf5/1.10.5.2/INTEL/19.0/lib/pkgconfig
     unload_module: darshan

```
However, when looking at any of the output logs, e.g. [test.log](
https://github.com/esmf-org/esmf-test-artifacts/blob/77cb6c99845f9786e818347fb2fe2b4e77f823d0/develop/intel/19.1.2/O/mpi/7.7.19/out/test.log#L57), you see that the extra environment variables are not set!

There are other configurations though where I see this feature working. So it's not clear why it is not working here...but it does make all tests fail (during build) on Cori, which is an issue of concern.
