### ISSUE TITLE
Allow combos to test just BOPT=O or just BOPT=g

### ISSUE THREAD

**Issue by billsacks** [esmf-org/esmf-test-scripts#90]
To allow faster testing on my laptop, I would like to just test with BOPT=g in my nightly testing. Currently, it is hard-coded that each combo runs both BOPT=O and BOPT=g. I propose adding a new optional entry under the mpi choices giving a list of BOPTs to test with. This would look like the following:

Instead of the current:

```yaml
matrix:
  gfortranclang:
    versions:
      12.2.0_14.0.0:
        compiler: gfortran-12.2.0_clang-14.0.0
        netcdf: netcdf-4.9.0
        mpi:
          openmpi:
            module: 4.1.4
```

we could have (see the last line):

```yaml
matrix:
  gfortranclang:
    versions:
      12.2.0_14.0.0:
        compiler: gfortran-12.2.0_clang-14.0.0
        netcdf: netcdf-4.9.0
        mpi:
          openmpi:
            module: 4.1.4
            bopt: [g]
```

or:

```yaml
matrix:
  gfortranclang:
    versions:
      12.2.0_14.0.0:
        compiler: gfortran-12.2.0_clang-14.0.0
        netcdf: netcdf-4.9.0
        mpi:
          openmpi:
            module: 4.1.4
            bopt: [O, g]
```

This would be optional; if the "bopt" entry is absent for a given MPI, it would default to [O, g].

I think this could be implemented with a couple lines of code in the Matrix `__init__` method. I'll do this unless anyone thinks this is a bad idea or should be done differently.

@theurich or others - let me know if you have thoughts on this.
